{% set name = "pyperclip" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 244035963e4428530d9e3a6101a1ef97209c6825edab1567beac148ccc1db1b6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  requires:
    - python
  imports:
    - pyperclip

about:
  home: https://github.com/asweigart/pyperclip
  license_file: LICENSE.txt
  license: BSD-3-Clause
  license_family: BSD
  summary: A cross-platform clipboard module for Python. (only handles plain text for now)
  description: |
    Pyperclip is a cross-platform Python module for copy and paste clipboard functions.
  dev_url: https://github.com/asweigart/pyperclip
  doc_url: https://pyperclip.readthedocs.io

extra:
  recipe-maintainers:
    - jan-janssen
    - ehfd
