{% set name = "pyperclip" %}
{% set version = "1.6.1" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "03ce3e66e2a26a085f0e043236dedd78aaabf53a64dab9a216671f74ee272845" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - pyperclip

about:
  home: https://github.com/asweigart/pyperclip
  license_file: {{ RECIPE_DIR }}/LICENSE.txt
  license: BSD 3-Clause
  license_family: BSD
  summary: 'A cross-platform clipboard module for Python. (only handles plain text for now)'
  dev_url: https://github.com/asweigart/pyperclip
  doc_url: https://pyperclip.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
