travis:
  secure:
    BINSTAR_TOKEN: pPfUTd1dlxN8itH/M2sGs7gINi5ScEpONsyFA8EIRNayir12yRagVGIiB5EAHS8XvJ5eMPBDijpzxr7HdhdDLtQ6XddGHOlBUItke9Waz/UrDtAb0A77Q3CJaNHkJeX867exmXnXa/fuASZmQ0Xg1VPw5xX8144+N2NRhznmFoeVZ6PyCRiLNERiVoKRqLldv4kz/54eWtkpGZ3N9DvRu2GbK9C7xT1D9NG7apeccnrrivbrg89pnPOiqtnYJWzRGlNvehCni+wMmbYl7jybZPEMC1fRZ8xhv39401JquBPrfl8Ojngi/0uceIFNyDbvOyKIdUEF2N0MFTNBSc/Pe7GRj40GPddh/2+pkeX/SeXIJohZSxj+Vbu4r2yJHtb7ZRDAIbPOCMcd48+JX+GSIZv554CitB5mwFRin1tmyIf4dE9IPGphwYA65MufCZY5mIfaTTPDl7kWoPQy8EqQIVZIynsm93KduiD/mlWrxaF+PMmAwfNHDCGd0N7/DY5n7PoKRpJ8NY4IE/XMN1Ijwsexszys5+UYu1umixByG3Zft/AOXJVHtrvkJlcYYJXItl6eoOJd4kn+FGotCBoWOuh2LKpsmZ3BKfh9jW7jCJWS1UJpaIpfXX4jxjavFL2n6pUGlY45RjEycmb3S0LgZns1N6ryfdjuOdPhtXZV6r8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
