travis:
  secure:
    BINSTAR_TOKEN: QYnXKYInzhb8ebtTgv2Vi02uXVBGAXMiif6H/omORtufai+Qi4GKO1SmvGFs9/MJFSIoLaRVd2GWIZ7Rj/J+Xy3ejd19xjOanR9cSazXPqwRcU1a1TGwokpWAytho3leGRafIUZoBn1Z2lGayORqtO6cNY1KG5WF25ZRQgso/BRS+x2iWo11/mMROmzBl6kjZfctI4G/LSY5elqPk6d8TNgTR2DIT5SmBR586fec+d3VNRGp6PEjMu2TIk6m2vfTLuzTQ8IA9J6vyIU/DTwiWMlp/UJiyhhBMxjmHdFOGGzbVb8CBEdO7bTCgazYop6OdSk8NCpoOL6J24nIbc5A46qy0OVMmXGuit1Mdzcyjg3SS3lE9J18xHZa4pslro/vRhwHOl1ZrYbT5CmDeo7uYbfkWKA+Rgs3aL82QudwqlhVmT3/NpNUjbT8aH5bxaB9weBsbRxwKxTwTvDuRLap5O5SchbmUhGSlQdix9FIWEOhLcHAgjgzdDx/cfHk4Qd2nOkyNJXOuswhwQqlSKnAFfL6rytSrmN/qc+GyHEY/EXisxbw4EsXQbcwIX4l06s6ye2cReQMJR2WpmK8/hbf7KlzbGSNO+d+E9XjnPjMumN3abpybtYxdEWfdixA2mQADwrIfOQKR1Grz6CwCFa1yiA47ArfpCFYLJdwTZrkCUs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
