travis:
  secure:
    BINSTAR_TOKEN: JGBglyq7E3+JfoHGjVpXSQeKXJTSpPflvCA7++osc8qD1TceT2pKr6FyV8igvOt0+e4XrMjsvOkY4Grsjkpliys7MOmSsuSQ8WNA58KOBxOFEEM0SibJ+MA8P2a9kO2IBPD9toyZ4dWa3ZLWc8dMi8PlJ6uLz4hXH6O1oy5C4egoOzyegqtq+bCiX/q5UsnYw0c8O1zlfAbBpQ/L/8BmHCbC0uJ0oujo8VRiqhwudt1FDCpNW0zSPoL8fVdfJ+8vcR7abe8zMVqmou4A8UJVY9y8UP8KuaPyPjpo3ALn/8QrmrVSphdzTiM1sc+aTTEeY6AMNKPkkb0Gmd23F6SFEIJ3ujkFlQL63nUdRjJku2qbRnIglh3YUmtl3K03r+Vu/2dYiKlptBbqYS2x0+6Cv2XPolHcOveHq/SqTcVeJvsdfe3oQqlHnzD4uWbnxcraICU+sGx6qj15Ri/vesrNYmLBzXPghXw9XA0E0QhWX+7nrk+/Ro5niJapPsKNBYZn/VFwE5AAHxjoBuGwUqkwHNZ3SsKA2o99EguMdFBPxG/dtV4cQxpsK1vEqI+pW0sBrVunRYzGTLmOogro5xdet2M8I2nasr/6VTHh9pOxi+E/B9elWBBcwRPRgcK6MCx1Dng0k1tcyK5sfOSDHwZipVx8Vj/2/n/9d/owl+JjwNw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
